### ISSUE TITLE
Interaction with mobile app

### ISSUE THREAD

**Issue by jdimeo** [surveycto/translation-tables#46]
I see that all the translation keys, except two "commons" keys, are prefixed with `webforms.` I assume that means they only apply to webforms only and not the mobile app, so any translation there would have to be through a different mechanism?

Say we define our own key `plugin.xyz.prompt=Do you want to continue`.

Will the mobile app "ignore" all keys (since these tables seem to be defined for webforms only) or will it still look up those keys and work the same between the app and webforms for those keys?

**Comment by meletis** [comment]
@jdimeo , thank you for your question. 

You have guessed it right. The files in this repository can only be used for the web forms. There is no mechanism right now for mobile app users to affect the translations there; the translations in the mobile app are maintained only by the SurveyCTO team for the moment.

**Comment by jdimeo** [comment]
Thanks @meletis  for the fast reply. I have to admit this is pretty surprising. If SurveyCTO was meant to be for one language and kind of found itself being used in a global context, I would understand, but as a fork of ODK it's designed for global field collection from day 1. The ability to customize via plugins is really powerful, but is almost completely negated if they can't be localized along with the rest of the form/survey.

**Comment by amrikcooper** [comment]
@jdimeo thanks for your comment! The SurveyCTO Collect app's interface is already localised into a range of other languages beyond English. Not only that, (and as you might be aware) question text and response options can be [localised into any language](https://docs.surveycto.com/02-designing-forms/04-sample-forms/02.translating.html). If you would like to learn more about Collect's language coverage, please get in touch via a more appropriate channel (I believe you're in touch with Maria) but you could also create a [support request](https://support.surveycto.com/hc/en-us/requests/new).

As for your points about field plug-ins, they do not depend on the translation table feature you're commenting on. They can be designed to behave dynamically in relation to the selected form language.

Where there are still gaps in Collect language coverage, we can discuss (via another channel, as above) possibly extending build-it support to meet your needs.

The feature you're commenting on was created to give web collect greater feature parity with Collect and works quite differently. You're welcome to make other comments about the translation tables in the context of their intended purpose but really, we might've entered [feature request](https://support.surveycto.com/hc/en-us/articles/360036824753-How-to-submit-a-feature-request) territory here (we'd be glad to engage with you on that front as well).
